# Generated by Django 3.0 on 2020-02-06 12:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 2, 6, 12, 8, 4, 920667, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
